### PR TITLE
Basic simulation page Part 1

### PR DESCRIPTION
**Pull request by colekniffen**
- Added axios package so we can transfer data from React to Rails

- Added amazon aws-sdk to yarn and rails so we can communicate with aws

- Created models for scenario and simulation

- Basic testing (still need to create system/view test but I just want to get this in)

- Very simple /dashboard/simulation/new view. I left an outline for how we will be handling the data output to our servies

There is still more to do here (i.e. sending the requests, making the code for the simulation page reusable, etc...) but the branch was getting thicc. So, this PR is intended to split it up

### CODE REVIEW

**Comment by colekniffen** [comment]
[Task 0027: Create a general design for the simulation request page](https://trello.com/c/RqTSZ8Ld/73-task-0027-create-a-general-design-for-the-simulation-request-page)

**Comment by colekniffen** [comment]
[Task 0030: Add scenario and simulation models](https://trello.com/c/FotLtOxM/76-task-0030-add-scenario-and-simulation-models)

**Comment by colekniffen** [comment]
[Task 0031: Add Axios and AWS-SDK packages](https://trello.com/c/tW5IQbGh/77-task-0031-add-axios-and-aws-sdk-packages)

**Comment by colekniffen** [comment]
[Task 0028: Create a barebones simulation request page](https://trello.com/c/hPtm1QvC/74-task-0028-create-a-barebones-simulation-request-page)

**Review by xxEoD2242 — APPROVED** [review]
Looks great!

**Pull request merged**
